#!/bin/bash

curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":0, "time":0}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":10, "time":7}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":20, "time":12}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":30, "time":15}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":38, "time":17}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":50, "time":20}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":90, "time":30}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":94, "time":31}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":106, "time":34}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":130, "time":40}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":134, "time":41}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":138, "time":42}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":158, "time":47}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":168, "time":49}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":170, "time":50}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":178, "time":52}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":190, "time":55}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"PREVISION",  "pk":200, "time":58}';echo

curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":0.1, "time":0.1}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":1.5, "time":3}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":3, "time":5}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":10, "time":10}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":12, "time":11}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":27, "time":17}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":40, "time":22}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":49, "time":25}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":58, "time":28}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":66, "time":30}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":85, "time":35}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":106, "time":41}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":114, "time":43}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":154, "time":50}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":163, "time":52}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":170, "time":54}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":175, "time":55}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":185, "time":57}';echo
curl -X POST 'http://localhost:9201/sncf/train' -d '{"train":"445", "matos":"MATOS_1", "simulation":"REEL",  "pk":200, "time":60}';echo
